### ISSUE TITLE
PlotlyJS testing

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#191]
I can't get the tests to work.  I need to be able to generate png files to pass into VisualRegressionTests, but I think Blink/electron might be too tricky to get working on travis?  Here's the latest errors:

```
PlotlyJS
[Plots.jl] Initializing backend: plotlyjs
INFO: Testing plot: plotlyjs:1:Lines
  Error :: (line:505)
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
    connect: connection refused (ECONNREFUSED)
     in yieldto at /Users/travis/julia/lib/julia/sys.dylib
     in wait at /Users/travis/julia/lib/julia/sys.dylib (repeats 2 times)
     in stream_wait at /Users/travis/julia/lib/julia/sys.dylib
     in wait_connected at /Users/travis/julia/lib/julia/sys.dylib
     in connect at socket.jl:671
     in try_connect at /Users/travis/.julia/v0.4/Blink/src/AtomShell/process.jl:58
     in init at /Users/travis/.julia/v0.4/Blink/src/AtomShell/process.jl:72
     in shell at /Users/travis/.julia/v0.4/Blink/src/AtomShell/process.jl:110
     in get_window at /Users/travis/.julia/v0.4/PlotlyJS/src/displays/electron.jl:30
     in get_window at /Users/travis/.julia/v0.4/PlotlyJS/src/displays/electron.jl:23
     in display at /Users/travis/.julia/v0.4/PlotlyJS/src/displays/electron.jl:47
     in _img_data at /Users/travis/.julia/v0.4/PlotlyJS/src/displays/electron.jl:73
     in writemime at /Users/travis/.julia/v0.4/PlotlyJS/src/savefig.jl:183
     in writemime at /Users/travis/.julia/v0.4/Plots/src/backends/plotlyjs.jl:11
     in png at /Users/travis/.julia/v0.4/Plots/src/output.jl:8
     in png at /Users/travis/.julia/v0.4/Plots/src/output.jl:11
     in anonymous at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:42
     in test_images at /Users/travis/.julia/v0.4/VisualRegressionTests/src/imgcomp.jl:79
     in image_comparison_tests at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:54
     in anonymous at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in do_fact at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:333
     [inlined code] from /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in image_comparison_facts at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:66
     in anonymous at /Users/travis/.julia/v0.4/Plots/test/runtests.jl:40
     in facts at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:448
     in include at /Users/travis/julia/lib/julia/sys.dylib
     in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
     in process_options at /Users/travis/julia/lib/julia/sys.dylib
     in _start at /Users/travis/julia/lib/julia/sys.dylib
INFO: Testing plot: plotlyjs:2:Functions, adding data, and animations
  Error :: (line:505)
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
    SystemError: fdopen: Bad file descriptor
     in call at libc.jl:49
     in call at libc.jl:54
     in writeimage at /Users/travis/.julia/v0.4/ImageMagick/src/libmagickwand.jl:255
     in writemime at /Users/travis/.julia/v0.4/PlotlyJS/src/savefig.jl:185
     in writemime at /Users/travis/.julia/v0.4/Plots/src/backends/plotlyjs.jl:11
     in png at /Users/travis/.julia/v0.4/Plots/src/output.jl:8
     in frame at /Users/travis/.julia/v0.4/Plots/src/animation.jl:15
     in frame at /Users/travis/.julia/v0.4/Plots/src/animation.jl:13
     [inlined code] from /Users/travis/.julia/v0.4/ExamplePlots/src/example_generation.jl:31
     in anonymous at no file:0
     in eval at /Users/travis/.julia/v0.4/Plots/test/runtests.jl:1
     in map_to! at abstractarray.jl:1286
     in map_to! at abstractarray.jl:1295
     in map at abstractarray.jl:1308
     in anonymous at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:41
     in test_images at /Users/travis/.julia/v0.4/VisualRegressionTests/src/imgcomp.jl:79
     in image_comparison_tests at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:54
     in anonymous at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in do_fact at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:333
     [inlined code] from /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in image_comparison_facts at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:66
     in anonymous at /Users/travis/.julia/v0.4/Plots/test/runtests.jl:40
     in facts at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:448
     in include at /Users/travis/julia/lib/julia/sys.dylib
     in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
     in process_options at /Users/travis/julia/lib/julia/sys.dylib
     in _start at /Users/travis/julia/lib/julia/sys.dylib
INFO: Testing plot: plotlyjs:3:Parametric plots
could not spawn `mkdir -p /Users/travis/.julia/v0.4/ExamplePlots/test/refimg/plotlyjs`: too many open files (EMFILE)  Error :: (line:505)
    Expression: image_comparison_tests(pkg,i,debug=debug,sigma=sigma,eps=eps) |> success --> true
    SystemError: opening file /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/juliaLlIL4B.png: Too many open files
     in open at /Users/travis/julia/lib/julia/sys.dylib (repeats 2 times)
     in png at /Users/travis/.julia/v0.4/Plots/src/output.jl:7
     in png at /Users/travis/.julia/v0.4/Plots/src/output.jl:11
     in anonymous at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:42
     in test_images at /Users/travis/.julia/v0.4/VisualRegressionTests/src/imgcomp.jl:79
     in image_comparison_tests at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:54
     in anonymous at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in do_fact at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:333
     [inlined code] from /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in image_comparison_facts at /Users/travis/.julia/v0.4/Plots/test/imgcomp.jl:66
     in anonymous at /Users/travis/.julia/v0.4/Plots/test/runtests.jl:40
     in facts at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:448
     in include at /Users/travis/julia/lib/julia/sys.dylib
     in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
     in process_options at /Users/travis/julia/lib/julia/sys.dylib
     in _start at /Users/travis/julia/lib/julia/sys.dylib
INFO: Testing plot: plotlyjs:4:Colors
could not spawn `mkdir -p /Users/travis/.julia/v0.4/ExamplePlots/test/refimg/plotlyjs`: too many open files (EMFILE)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by spencerlyon2** [comment]
Blink definitely is tricky to get working on travis, but you can see from our [very comprehensive test suite](https://github.com/JunoLab/Blink.jl/blob/master/test/runtests.jl) that it is possible to communicate back and forth.

You might want to take a look at the travis file: https://github.com/JunoLab/Blink.jl/blob/master/.travis.yml

Specifically the deal with `TESTCMD` and using `xvfb-run` on linux

**Comment by tbreloff** [comment]
Thanks... trying again!

**Comment by tbreloff** [comment]
No luck.  

My travis file looks like:

```
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

# borrowed from Blink.jl's travis file
matrix:
  include:
    - os: linux
      julia: 0.4
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.4
      env: TESTCMD="julia"
      
notifications:
  email: true
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("Plots")'Pkg.checkout("Images","tom_imgcompare");'
 - julia -e 'Pkg.clone("https://github.com/tbreloff/ImageMagick.jl.git"); Pkg.checkout("ImageMagick","tb_write"); Pkg.build("ImageMagick")'
 - julia -e 'Pkg.clone("https://github.com/tbreloff/VisualRegressionTests.jl.git");'
 - julia -e 'Pkg.clone("https://github.com/tbreloff/ExamplePlots.jl.git");'
 - julia -e 'Pkg.clone("https://github.com/JunoLab/Blink.jl.git"); Pkg.build("Blink"); import Blink; Blink.AtomShell.install()'
 - julia -e 'Pkg.clone("https://github.com/spencerlyon2/PlotlyJS.jl.git")'
 - julia -e 'ENV["PYTHON"] = ""; Pkg.add("PyPlot"); Pkg.build("PyPlot")'
 - julia -e 'Pkg.test("Plots"; coverage=false)'Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
```
